name: Metrics

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_skipped: metrics
